import { BookOpen, CircleAlert, Database, GitBranch, Ruler, Scale, ShieldCheck } from 'lucide-react';
import { AquaShell, Card, PageIntro, SectionLabel } from '@/components/aqua-shell';

const principles = [
  { icon: Database, title: 'Dataset before dashboard', body: 'Every summary starts with the observed records available to the API. Synthetic or incomplete data is labeled rather than polished away.' },
  { icon: GitBranch, title: 'A model is a lens', body: 'Predictions are model outputs conditioned on the supplied scenario. They support a question; they do not replace a meter, audit, or agronomist.' },
  { icon: Scale, title: 'Comparisons need a baseline', body: 'Scenario deltas hold the rest of the inputs steady so a change can be inspected. Real-world savings depend on timing, execution, and local constraints.' },
];

export default function About() {
  return <AquaShell><PageIntro eyebrow="Field notes / 08" title="Methodology, made legible." description="AquaCrop AI is a workspace for asking better water questions. This page keeps the boundaries of the answer visible." />
    <div className="space-y-6"><Card className="overflow-hidden"><div className="grid gap-0 lg:grid-cols-[1.1fr_.9fr]"><div className="bg-primary p-7 text-primary-foreground sm:p-10"><div className="mb-10 flex h-11 w-11 items-center justify-center rounded-xl bg-primary-foreground/10"><BookOpen size={21} /></div><p className="font-data text-[10px] uppercase tracking-[.18em] text-primary-foreground/60">The short version</p><h2 className="mt-3 max-w-lg font-display text-4xl leading-[.98] tracking-[-.04em] sm:text-5xl">Use the estimate to sharpen the next question.</h2><p className="mt-5 max-w-md text-sm leading-6 text-primary-foreground/72">Water footprints are shaped by inputs, definitions, and context. AquaCrop AI makes those ingredients inspectable so a confident number never masquerades as ground truth.</p></div><div className="p-7 sm:p-10"><SectionLabel>How a prediction travels</SectionLabel><div className="space-y-6">{['Capture the crop, weather, field, and management assumptions.', 'Pass the scenario to the selected trained model.', 'Return the footprint with category, drivers, and methodology note.', 'Save the scenario when the assumptions are worth revisiting.'].map((step, index) => <div key={step} className="flex gap-4"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-accent font-data text-xs text-accent-foreground">{index + 1}</span><p className="pt-1 text-sm leading-5">{step}</p></div>)}</div></div></div></Card>
      <div className="grid gap-6 lg:grid-cols-3">{principles.map(({ icon: Icon, title, body }) => <Card key={title} className="p-6"><div className="grid h-10 w-10 place-items-center rounded-lg bg-primary/10 text-primary"><Icon size={19} /></div><h2 className="mt-5 text-sm font-extrabold">{title}</h2><p className="mt-2 text-xs leading-5 text-muted-foreground">{body}</p></Card>)}</div>
      <div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><Card className="p-6"><SectionLabel>What to say in a viva</SectionLabel><h2 className="font-display text-3xl">Be precise about uncertainty.</h2><div className="mt-5 space-y-3 text-xs leading-5 text-muted-foreground"><p><strong className="text-foreground">Inputs:</strong> describe which conditions were supplied, and which were left unspecified.</p><p><strong className="text-foreground">Validation:</strong> report the method and metrics shown in Performance, not a universal accuracy claim.</p><p><strong className="text-foreground">Use:</strong> present outputs as decision support for testing and prioritization.</p></div></Card><Card className="p-6"><div className="flex items-start gap-3"><CircleAlert size={18} className="mt-0.5 shrink-0 text-accent-foreground" /><div><SectionLabel>Limitations to keep visible</SectionLabel><ul className="space-y-3 text-xs leading-5 text-muted-foreground"><li>• Historical observations may not represent every soil, season, or irrigation practice.</li><li>• Feature importance describes model behavior, not necessarily biological causation.</li><li>• A modeled footprint is not a direct measurement of water withdrawn or consumed.</li><li>• Recommendations should be reviewed with local agronomic and operational knowledge.</li></ul></div></div></Card></div>
      <div className="flex flex-wrap items-center gap-x-8 gap-y-3 rounded-xl border border-border bg-muted/25 px-6 py-5 text-[11px] text-muted-foreground"><span className="flex items-center gap-2"><Ruler size={14} className="text-primary" />Units: L per kg</span><span className="flex items-center gap-2"><ShieldCheck size={14} className="text-primary" />Scenario assumptions retained</span><span className="flex items-center gap-2"><Database size={14} className="text-primary" />Source disclosed in Overview</span></div>
    </div>
  </AquaShell>;
}