import { useMemo, useState } from 'react';
import { ArrowDownUp, BarChart3, Search } from 'lucide-react';
import { useGetCropFootprints } from '@workspace/api-client-react';
import { AquaShell, Card, EmptyBlock, ErrorBlock, LoadingBlock, PageIntro, SectionLabel, fmt } from '@/components/aqua-shell';
import { Input } from '@/components/forms';

export default function Compare() {
  const query = useGetCropFootprints();
  const [search, setSearch] = useState('');
  const [sort, setSort] = useState<'low' | 'high'>('low');
  const crops = useMemo(() => (query.data ?? []).filter((item) => item.crop.toLowerCase().includes(search.toLowerCase())).sort((a, b) => sort === 'low' ? a.averageFootprint - b.averageFootprint : b.averageFootprint - a.averageFootprint), [query.data, search, sort]);
  const max = Math.max(...(query.data?.map((item) => item.maxFootprint) ?? [1]));
  return <AquaShell><PageIntro eyebrow="Dataset lens / 03" title="Compare the footprints." description="Observed crop summaries make the spread visible. Sort for efficiency, search when the field is specific." action={<div className="flex items-center gap-2 rounded-lg border border-border bg-card px-3 py-2 text-xs text-muted-foreground"><BarChart3 size={15} className="text-primary" />{query.data?.length ?? 0} crop profiles</div>} />
    {query.isLoading ? <LoadingBlock rows={7} /> : query.isError ? <ErrorBlock onRetry={() => query.refetch()} /> : crops.length === 0 ? <EmptyBlock title="No matching profiles" body="Try a different crop name, or wait for the dataset feed to return observations." /> : <Card className="overflow-hidden"><div className="flex flex-col justify-between gap-4 border-b border-border bg-muted/25 p-5 md:flex-row md:items-center"><div className="relative w-full max-w-sm"><Search size={15} className="absolute left-3 top-3 text-muted-foreground" /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Find a crop…" className="pl-9" data-testid="input-search-crops" /></div><button onClick={() => setSort(sort === 'low' ? 'high' : 'low')} data-testid="button-sort-footprints" className="inline-flex items-center gap-2 self-start rounded-lg border border-border bg-card px-3 py-2.5 text-xs font-bold hover-elevate md:self-auto"><ArrowDownUp size={14} />{sort === 'low' ? 'Lowest first' : 'Highest first'}</button></div><div className="hidden grid-cols-[1.2fr_1.2fr_.6fr_.6fr_.6fr] gap-4 border-b border-border px-6 py-3 font-data text-[10px] uppercase tracking-[0.15em] text-muted-foreground md:grid"><span>Crop</span><span>Observed spread</span><span>Average</span><span>Range</span><span>Rows</span></div><div>{crops.map((item, index) => <div key={item.crop} data-testid={`row-comparison-${index}`} className="grid gap-3 border-b border-border/70 px-5 py-4 last:border-0 md:grid-cols-[1.2fr_1.2fr_.6fr_.6fr_.6fr] md:items-center md:gap-4 md:px-6"><div><p className="text-sm font-bold">{item.crop}</p><p className="mt-1 text-[10px] text-muted-foreground md:hidden">{item.observations.toLocaleString()} observations</p></div><div className="flex h-3 items-center gap-2"><div className="relative h-1.5 flex-1 rounded-full bg-muted"><span className="absolute h-full rounded-full bg-primary/80" style={{ left: `${(item.minFootprint / max) * 100}%`, width: `${Math.max(2, ((item.maxFootprint - item.minFootprint) / max) * 100)}%` }} /></div></div><span className="font-data text-sm text-primary">{fmt(item.averageFootprint)} <small className="font-sans text-[10px] text-muted-foreground">L/kg</small></span><span className="text-xs text-muted-foreground">{fmt(item.minFootprint)} — {fmt(item.maxFootprint)}</span><span className="font-data text-xs text-muted-foreground">{item.observations.toLocaleString()}</span></div>)}</div><div className="flex items-center gap-2 bg-accent/10 px-6 py-4 text-[11px] text-muted-foreground"><span className="h-2 w-2 rounded-full bg-accent" />Observed summaries, not causal comparisons. Differences reflect this dataset's conditions.</div></Card>}
  </AquaShell>;
}